name: Deploy to AWS Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/ovapi:latest

      - name: Install and configure AWS CLI
        run: |
          pip install awscli
          aws configure set default.region YOUR_AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Beanstalk
        run: |
          aws s3 cp Dockerrun.aws.json s3://ovapi-artifacts/Dockerrun.aws.json
          aws elasticbeanstalk create-application-version --application-name ovapi --version-label ${{ github.sha }} --source-bundle S3Bucket=ovapi-artifacts,S3Key=Dockerrun.aws.json
          aws elasticbeanstalk update-environment --environment-name Ovapi-env --version-label ${{ github.sha }}
